name: Daily Check-up

on:
  workflow_dispatch:    # Allows manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at 00:00 UTC

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  daily-check:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Needed to commit and push changes

      - name: Set up Git
        shell: pwsh
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract default textures
        shell: pwsh
        run: |
          .\.github\scripts\extract.ps1

      - name: Ignore unwanted files
        shell: pwsh
        run: |
          .\.github\scripts\ignore.ps1

      - name: Sync assets from Faithful 32x repository
        shell: pwsh
        run: |
          .\.github\scripts\sync.ps1

      - name: Prune extra textures
        shell: pwsh
        run: |
          .\.github\scripts\status.ps1 -PruneExtra

      - name: Commit synced assets
        shell: pwsh
        run: |
          .\.github\scripts\git.ps1 -CommitMessage "daily sync assets from Faithful 32x" -NoPush

      - name: Update Assets under Watch
        shell: pwsh
        run: |
          .\.github\scripts\watcher.ps1

      - name: Update progression in README
        shell: pwsh
        run: |
          .\.github\scripts\progress.ps1

      - name: Commit and push changes
        shell: pwsh
        run: |
          .\.github\scripts\git.ps1 -CommitMessage "daily synchronization and updates"