name: Update Progress Bar on README

on:
  schedule:
    - cron: "5 2 * * *" # Runs daily at 2:05 AM UTC
  workflow_dispatch:    # Allows manual trigger

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  update-progress:
    runs-on: windows-latest # Using Windows for PowerShell support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to commit and push changes

      - name: Set up Git
        shell: pwsh
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Extract Script
        shell: pwsh
        run: |
          .\.github\scripts\extract.ps1
          
      - name: Generate Progress Statistics
        shell: pwsh
        run: |
          .\.github\scripts\progress.ps1

      - name: Commit and push changes
        run: |
          .\.github\scripts\push.ps1 -CommitMessage "chore: update progression bars on README"

