name: Sync Vanilla 32x Assets

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:    # Allows manual trigger

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  sync-assets:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to commit and push changes

      - name: Set up Git
        shell: pwsh
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync assets from Faithful 32x repository
        shell: pwsh
        run: |
          .\.github\scripts\sync.ps1

      - name: Prune Extra Textures
        shell: pwsh
        run: |
          .\.github\scripts\extract.ps1;
          .\.github\scripts\status.ps1 -PruneExtra

      - name: Commit and push changes
        shell: pwsh
        run: |
          .\.github\scripts\push.ps1 -CommitMessage "sync assets from Faithful 32x"
